# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55bf304a4d41ef066879843271490e737cb17ea239801d0651596d79e246753981fdf88a3c249a5010f51252ab7868e52e691efb44a7d050d9aad2500683351b

test:
  secret_key_base: e26580d7b02b32e3d28ceb4d804c772d7409a3ba6a444d3270060651f89b0064fe1dc38d9ce33875d3ea09238de9025464acf7f7db90a06af92575be408d5dad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
